name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Initialise
        run: Preparing deploy files...

      - name: Build and deploy
        run: |
          docker-compose up --build
          git push origin HEAD:gh-pages --force
